services:
  - type: web
    name: kcp-estimate
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libreoffice-writer libreoffice-calc libreoffice-impress libreoffice-draw libreoffice-math libreoffice-base libreoffice-gnome libreoffice-gtk3 && \
      pip install -r requirements.txt && \
      python manage.py collectstatic --no-input && \
      python manage.py migrate
    startCommand: gunicorn kcp_estimate.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 