# Generated by Django 5.0.2 on 2025-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or terms and conditions"
            ),
        ),
    ]
